#### Synopsys synthesis constraints file created by FPGA I/O Optimizer
#### Mon Jun 29 12:47:43 2020

# set_vendor xilinx
# set_family spartan-7
# set_device 7s100
# set_package fgga676
# set_speed -2
setup_design -manufacturer "xilinx" -family "spartan-7" -part "7s100" -package "fgga676" -speed "-2"
set_attribute -name PIN_NUMBER -value AC19 -port ADC0_CLOCK_P
set_attribute -name PIN_NUMBER -value AD19 -port ADC0_CLOCK_M
set_attribute -name PIN_NUMBER -value AC16 -port ADC0_DA0P
set_attribute -name PIN_NUMBER -value AD16 -port ADC0_DA0M
set_attribute -name PIN_NUMBER -value AA17 -port ADC0_DA1P
set_attribute -name PIN_NUMBER -value AA18 -port ADC0_DA1M
set_attribute -name PIN_NUMBER -value AD15 -port ADC0_DB0P
set_attribute -name PIN_NUMBER -value AE16 -port ADC0_DB0M
set_attribute -name PIN_NUMBER -value AB17 -port ADC0_DB1P
set_attribute -name PIN_NUMBER -value AC17 -port ADC0_DB1M
set_attribute -name PIN_NUMBER -value AE15 -port ADC0_DC0P
set_attribute -name PIN_NUMBER -value AF15 -port ADC0_DC0M
set_attribute -name PIN_NUMBER -value AC18 -port ADC0_DC1P
set_attribute -name PIN_NUMBER -value AD18 -port ADC0_DC1M
set_attribute -name PIN_NUMBER -value AE20 -port ADC0_DCLK_P
set_attribute -name PIN_NUMBER -value AF20 -port ADC0_DCLK_M
set_attribute -name PIN_NUMBER -value AF17 -port ADC0_DD0P
set_attribute -name PIN_NUMBER -value AF18 -port ADC0_DD0M
set_attribute -name PIN_NUMBER -value AE18 -port ADC0_DD1P
set_attribute -name PIN_NUMBER -value AF19 -port ADC0_DD1M
set_attribute -name PIN_NUMBER -value AA19 -port ADC0_FCLK_P
set_attribute -name PIN_NUMBER -value AB19 -port ADC0_FCLK_M
set_attribute -name PIN_NUMBER -value U26 -port ADC0_SDOUT
set_attribute -name PIN_NUMBER -value AE17 -port ADC0_SEN
set_attribute -name PIN_NUMBER -value AD20 -port ADC0_SYSRF_P
set_attribute -name PIN_NUMBER -value AE21 -port ADC0_SYSRF_M
set_attribute -name PIN_NUMBER -value AD24 -port ADC1_CLOCK_P
set_attribute -name PIN_NUMBER -value AD25 -port ADC1_CLOCK_M
set_attribute -name PIN_NUMBER -value AB22 -port ADC1_DA0P
set_attribute -name PIN_NUMBER -value AC22 -port ADC1_DA0M
set_attribute -name PIN_NUMBER -value AA20 -port ADC1_DA1P
set_attribute -name PIN_NUMBER -value AB20 -port ADC1_DA1M
set_attribute -name PIN_NUMBER -value AF22 -port ADC1_DB0P
set_attribute -name PIN_NUMBER -value AF23 -port ADC1_DB0M
set_attribute -name PIN_NUMBER -value AD23 -port ADC1_DB1P
set_attribute -name PIN_NUMBER -value AE23 -port ADC1_DB1M
set_attribute -name PIN_NUMBER -value AC23 -port ADC1_DC0P
set_attribute -name PIN_NUMBER -value AC24 -port ADC1_DC0M
set_attribute -name PIN_NUMBER -value AB24 -port ADC1_DC1P
set_attribute -name PIN_NUMBER -value AB25 -port ADC1_DC1M
set_attribute -name PIN_NUMBER -value AB21 -port ADC1_DCLK_P
set_attribute -name PIN_NUMBER -value AC21 -port ADC1_DCLK_M
set_attribute -name PIN_NUMBER -value AB26 -port ADC1_DD0P
set_attribute -name PIN_NUMBER -value AC26 -port ADC1_DD0M
set_attribute -name PIN_NUMBER -value AD26 -port ADC1_DD1P
set_attribute -name PIN_NUMBER -value AE26 -port ADC1_DD1M
set_attribute -name PIN_NUMBER -value AD21 -port ADC1_FCLK_P
set_attribute -name PIN_NUMBER -value AE22 -port ADC1_FCLK_M
set_attribute -name PIN_NUMBER -value AF24 -port ADC1_SEN
set_attribute -name PIN_NUMBER -value AE25 -port ADC1_SYSRF_P
set_attribute -name PIN_NUMBER -value AF25 -port ADC1_SYSRF_M
set_attribute -name PIN_NUMBER -value V23 -port ADC2_CLOCK_P
set_attribute -name PIN_NUMBER -value W24 -port ADC2_CLOCK_M
set_attribute -name PIN_NUMBER -value W20 -port ADC2_DA0P
set_attribute -name PIN_NUMBER -value W21 -port ADC2_DA0M
set_attribute -name PIN_NUMBER -value Y21 -port ADC2_DA1P
set_attribute -name PIN_NUMBER -value Y22 -port ADC2_DA1M
set_attribute -name PIN_NUMBER -value AA22 -port ADC2_DB0P
set_attribute -name PIN_NUMBER -value AA23 -port ADC2_DB0M
set_attribute -name PIN_NUMBER -value V21 -port ADC2_DB1P
set_attribute -name PIN_NUMBER -value V22 -port ADC2_DB1M
set_attribute -name PIN_NUMBER -value AA24 -port ADC2_DC0P
set_attribute -name PIN_NUMBER -value AA25 -port ADC2_DC0M
set_attribute -name PIN_NUMBER -value W23 -port ADC2_DC1P
set_attribute -name PIN_NUMBER -value Y23 -port ADC2_DC1M
set_attribute -name PIN_NUMBER -value T22 -port ADC2_DCLK_P
set_attribute -name PIN_NUMBER -value U22 -port ADC2_DCLK_M
set_attribute -name PIN_NUMBER -value Y25 -port ADC2_DD0P
set_attribute -name PIN_NUMBER -value Y26 -port ADC2_DD0M
set_attribute -name PIN_NUMBER -value W25 -port ADC2_DD1P
set_attribute -name PIN_NUMBER -value W26 -port ADC2_DD1M
set_attribute -name PIN_NUMBER -value U20 -port ADC2_FCLK_P
set_attribute -name PIN_NUMBER -value U21 -port ADC2_FCLK_M
set_attribute -name PIN_NUMBER -value R23 -port ADC2_SEN
set_attribute -name PIN_NUMBER -value U24 -port ADC2_SYSRF_P
set_attribute -name PIN_NUMBER -value V24 -port ADC2_SYSRF_M
set_attribute -name PIN_NUMBER -value K25 -port ADC3_CLOCK_P
set_attribute -name PIN_NUMBER -value K26 -port ADC3_CLOCK_M
set_attribute -name PIN_NUMBER -value M22 -port ADC3_DA0P
set_attribute -name PIN_NUMBER -value L23 -port ADC3_DA0M
set_attribute -name PIN_NUMBER -value M20 -port ADC3_DA1P
set_attribute -name PIN_NUMBER -value M21 -port ADC3_DA1M
set_attribute -name PIN_NUMBER -value M24 -port ADC3_DB0P
set_attribute -name PIN_NUMBER -value L24 -port ADC3_DB0M
set_attribute -name PIN_NUMBER -value M25 -port ADC3_DB1P
set_attribute -name PIN_NUMBER -value L25 -port ADC3_DB1M
set_attribute -name PIN_NUMBER -value L22 -port ADC3_DC0P
set_attribute -name PIN_NUMBER -value K23 -port ADC3_DC0M
set_attribute -name PIN_NUMBER -value L20 -port ADC3_DC1P
set_attribute -name PIN_NUMBER -value K20 -port ADC3_DC1M
set_attribute -name PIN_NUMBER -value J23 -port ADC3_DCLK_P
set_attribute -name PIN_NUMBER -value H23 -port ADC3_DCLK_M
set_attribute -name PIN_NUMBER -value J24 -port ADC3_DD0P
set_attribute -name PIN_NUMBER -value J25 -port ADC3_DD0M
set_attribute -name PIN_NUMBER -value J26 -port ADC3_DD1P
set_attribute -name PIN_NUMBER -value H26 -port ADC3_DD1M
set_attribute -name PIN_NUMBER -value G22 -port ADC3_FCLK_P
set_attribute -name PIN_NUMBER -value F22 -port ADC3_FCLK_M
set_attribute -name PIN_NUMBER -value H22 -port ADC3_SEN
set_attribute -name PIN_NUMBER -value H24 -port ADC3_SYSRF_P
set_attribute -name PIN_NUMBER -value G24 -port ADC3_SYSRF_M
set_attribute -name PIN_NUMBER -value G20 -port ADC4_CLOCK_P
set_attribute -name PIN_NUMBER -value G21 -port ADC4_CLOCK_M
set_attribute -name PIN_NUMBER -value K21 -port ADC4_DA0P
set_attribute -name PIN_NUMBER -value K22 -port ADC4_DA0M
set_attribute -name PIN_NUMBER -value G25 -port ADC4_DA1P
set_attribute -name PIN_NUMBER -value G26 -port ADC4_DA1M
set_attribute -name PIN_NUMBER -value J20 -port ADC4_DB0P
set_attribute -name PIN_NUMBER -value H21 -port ADC4_DB0M
set_attribute -name PIN_NUMBER -value F24 -port ADC4_DB1P
set_attribute -name PIN_NUMBER -value F25 -port ADC4_DB1M
set_attribute -name PIN_NUMBER -value J19 -port ADC4_DC0P
set_attribute -name PIN_NUMBER -value H19 -port ADC4_DC0M
set_attribute -name PIN_NUMBER -value E22 -port ADC4_DC1P
set_attribute -name PIN_NUMBER -value D23 -port ADC4_DC1M
set_attribute -name PIN_NUMBER -value E25 -port ADC4_DCLK_P
set_attribute -name PIN_NUMBER -value E26 -port ADC4_DCLK_M
set_attribute -name PIN_NUMBER -value D24 -port ADC4_DD0P
set_attribute -name PIN_NUMBER -value D25 -port ADC4_DD0M
set_attribute -name PIN_NUMBER -value F23 -port ADC4_DD1P
set_attribute -name PIN_NUMBER -value E23 -port ADC4_DD1M
set_attribute -name PIN_NUMBER -value D26 -port ADC4_FCLK_P
set_attribute -name PIN_NUMBER -value C26 -port ADC4_FCLK_M
set_attribute -name PIN_NUMBER -value J21 -port ADC4_SEN
set_attribute -name PIN_NUMBER -value B25 -port ADC4_SYSRF_P
set_attribute -name PIN_NUMBER -value B26 -port ADC4_SYSRF_M
set_attribute -name PIN_NUMBER -value B19 -port ADC5_CLOCK_P
set_attribute -name PIN_NUMBER -value B20 -port ADC5_CLOCK_M
set_attribute -name PIN_NUMBER -value A24 -port ADC5_DA0P
set_attribute -name PIN_NUMBER -value A25 -port ADC5_DA0M
set_attribute -name PIN_NUMBER -value C24 -port ADC5_DA1P
set_attribute -name PIN_NUMBER -value B24 -port ADC5_DA1M
set_attribute -name PIN_NUMBER -value C22 -port ADC5_DB0P
set_attribute -name PIN_NUMBER -value C23 -port ADC5_DB0M
set_attribute -name PIN_NUMBER -value A22 -port ADC5_DB1P
set_attribute -name PIN_NUMBER -value A23 -port ADC5_DB1M
set_attribute -name PIN_NUMBER -value D21 -port ADC5_DC0P
set_attribute -name PIN_NUMBER -value C21 -port ADC5_DC0M
set_attribute -name PIN_NUMBER -value B21 -port ADC5_DC1P
set_attribute -name PIN_NUMBER -value B22 -port ADC5_DC1M
set_attribute -name PIN_NUMBER -value E20 -port ADC5_DCLK_P
set_attribute -name PIN_NUMBER -value E21 -port ADC5_DCLK_M
set_attribute -name PIN_NUMBER -value F19 -port ADC5_DD0P
set_attribute -name PIN_NUMBER -value F20 -port ADC5_DD0M
set_attribute -name PIN_NUMBER -value A19 -port ADC5_DD1P
set_attribute -name PIN_NUMBER -value A20 -port ADC5_DD1M
set_attribute -name PIN_NUMBER -value D18 -port ADC5_FCLK_P
set_attribute -name PIN_NUMBER -value C19 -port ADC5_FCLK_M
set_attribute -name PIN_NUMBER -value G19 -port ADC5_SEN
set_attribute -name PIN_NUMBER -value D19 -port ADC5_SYSRF_P
set_attribute -name PIN_NUMBER -value D20 -port ADC5_SYSRF_M
set_attribute -name PIN_NUMBER -value P25 -port ADC_RESET
set_attribute -name PIN_NUMBER -value P26 -port ADC_SCLKR
set_attribute -name PIN_NUMBER -value T25 -port ADC_SDATAR
set_attribute -name PIN_NUMBER -value T5 -port DAC0_DIN
set_attribute -name PIN_NUMBER -value P6 -port DAC0_nSYNC0
set_attribute -name PIN_NUMBER -value R7 -port DAC0_nSYNC1
set_attribute -name PIN_NUMBER -value R6 -port DAC0_nSYNC2
set_attribute -name PIN_NUMBER -value R5 -port DAC0_SCLK
set_attribute -name PIN_NUMBER -value W1 -port DAC1_DIN
set_attribute -name PIN_NUMBER -value T2 -port DAC1_nSYNC0
set_attribute -name PIN_NUMBER -value R2 -port DAC1_nSYNC1
set_attribute -name PIN_NUMBER -value P4 -port DAC1_nSYNC2
set_attribute -name PIN_NUMBER -value R3 -port DAC1_SCLK
set_attribute -name PIN_NUMBER -value V3 -port DAC2_DIN
set_attribute -name PIN_NUMBER -value AA2 -port DAC2_nSYNC1
set_attribute -name PIN_NUMBER -value Y3 -port DAC2_nSYNC2
set_attribute -name PIN_NUMBER -value Y1 -port DAC2_SCLK
set_attribute -name PIN_NUMBER -value D4 -port DDR3_A0
set_attribute -name PIN_NUMBER -value D3 -port DDR3_A1
set_attribute -name PIN_NUMBER -value D1 -port DDR3_A2
set_attribute -name PIN_NUMBER -value C1 -port DDR3_A3
set_attribute -name PIN_NUMBER -value A3 -port DDR3_A4
set_attribute -name PIN_NUMBER -value A2 -port DDR3_A5
set_attribute -name PIN_NUMBER -value C4 -port DDR3_A6
set_attribute -name PIN_NUMBER -value B4 -port DDR3_A7
set_attribute -name PIN_NUMBER -value C3 -port DDR3_A8
set_attribute -name PIN_NUMBER -value B5 -port DDR3_A9
set_attribute -name PIN_NUMBER -value A5 -port DDR3_A10
set_attribute -name PIN_NUMBER -value E5 -port DDR3_A11
set_attribute -name PIN_NUMBER -value D5 -port DDR3_A12
set_attribute -name PIN_NUMBER -value F7 -port DDR3_A13
set_attribute -name PIN_NUMBER -value D6 -port DDR3_BA0
set_attribute -name PIN_NUMBER -value E7 -port DDR3_BA1
set_attribute -name PIN_NUMBER -value E6 -port DDR3_BA2
set_attribute -name PIN_NUMBER -value B2 -port DDR3_CK_P
set_attribute -name PIN_NUMBER -value B1 -port DDR3_CK_N
set_attribute -name PIN_NUMBER -value C2 -port DDR3_CKE
set_attribute -name PIN_NUMBER -value D8 -port DDR3_CLK100
set_attribute -name PIN_NUMBER -value F5 -port DDR3_CLK100_OUT
set_attribute -name PIN_NUMBER -value B12 -port DDR3_DM1
set_attribute -name PIN_NUMBER -value D9 -port DDR3_DM0
set_attribute -name PIN_NUMBER -value A8 -port DDR3_DQ0
set_attribute -name PIN_NUMBER -value A7 -port DDR3_DQ1
set_attribute -name PIN_NUMBER -value F10 -port DDR3_DQ2
set_attribute -name PIN_NUMBER -value F9 -port DDR3_DQ3
set_attribute -name PIN_NUMBER -value C9 -port DDR3_DQ4
set_attribute -name PIN_NUMBER -value C8 -port DDR3_DQ5
set_attribute -name PIN_NUMBER -value F8 -port DDR3_DQ6
set_attribute -name PIN_NUMBER -value E8 -port DDR3_DQ7
set_attribute -name PIN_NUMBER -value C12 -port DDR3_DQ8
set_attribute -name PIN_NUMBER -value C11 -port DDR3_DQ9
set_attribute -name PIN_NUMBER -value B10 -port DDR3_DQ10
set_attribute -name PIN_NUMBER -value A10 -port DDR3_DQ11
set_attribute -name PIN_NUMBER -value F12 -port DDR3_DQ12
set_attribute -name PIN_NUMBER -value E12 -port DDR3_DQ13
set_attribute -name PIN_NUMBER -value E11 -port DDR3_DQ14
set_attribute -name PIN_NUMBER -value E10 -port DDR3_DQ15
set_attribute -name PIN_NUMBER -value B9 -port DDR3_DQS0_P
set_attribute -name PIN_NUMBER -value A9 -port DDR3_DQS0_N
set_attribute -name PIN_NUMBER -value D11 -port DDR3_DQS1_P
set_attribute -name PIN_NUMBER -value D10 -port DDR3_DQS1_N
set_attribute -name PIN_NUMBER -value P3 -port DDR3_LDM
set_attribute -name PIN_NUMBER -value B6 -port DDR3_nCAS
set_attribute -name PIN_NUMBER -value C6 -port DDR3_nCS
set_attribute -name PIN_NUMBER -value C7 -port DDR3_nRAS
set_attribute -name PIN_NUMBER -value A4 -port DDR3_nRESET
set_attribute -name PIN_NUMBER -value B7 -port DDR3_nWE
set_attribute -name PIN_NUMBER -value A12 -port DDR3_ODT
set_attribute -name PIN_NUMBER -value AB2 -port DDR3_UDM
set_attribute -name PIN_NUMBER -value AA7 -port DDR3_VTT_S3
set_attribute -name PIN_NUMBER -value Y7 -port DDR3_VTT_S5
set_attribute -name PIN_NUMBER -value AD1 -port DISCR_OUT0
set_attribute -name PIN_NUMBER -value AC3 -port DISCR_OUT1
set_attribute -name PIN_NUMBER -value AF3 -port DISCR_OUT2
set_attribute -name PIN_NUMBER -value AF5 -port DISCR_OUT3
set_attribute -name PIN_NUMBER -value AC4 -port DISCR_OUT4
set_attribute -name PIN_NUMBER -value AD3 -port DISCR_OUT5
set_attribute -name PIN_NUMBER -value AE6 -port DISCR_OUT6
set_attribute -name PIN_NUMBER -value AD6 -port DISCR_OUT7
set_attribute -name PIN_NUMBER -value AA8 -port DISCR_OUT8
set_attribute -name PIN_NUMBER -value AB6 -port DISCR_OUT9
set_attribute -name PIN_NUMBER -value AC8 -port DISCR_OUT10
set_attribute -name PIN_NUMBER -value AE8 -port DISCR_OUT11
set_attribute -name PIN_NUMBER -value AD14 -port DISCR_OUT12
set_attribute -name PIN_NUMBER -value AB11 -port DISCR_OUT13
set_attribute -name PIN_NUMBER -value AF14 -port DISCR_OUT14
set_attribute -name PIN_NUMBER -value AE11 -port DISCR_OUT15
set_attribute -name PIN_NUMBER -value AE12 -port DISCR_OUT16
set_attribute -name PIN_NUMBER -value AC12 -port DISCR_OUT17
set_attribute -name PIN_NUMBER -value AA9 -port DISCR_OUT18
set_attribute -name PIN_NUMBER -value AF10 -port DISCR_OUT19
set_attribute -name PIN_NUMBER -value AD10 -port DISCR_OUT20
set_attribute -name PIN_NUMBER -value AC9 -port DISCR_OUT21
set_attribute -name PIN_NUMBER -value AF8 -port DISCR_OUT22
set_attribute -name PIN_NUMBER -value AA10 -port DISCR_OUT23
set_attribute -name PIN_NUMBER -value J1 -port FMC_A0
set_attribute -name PIN_NUMBER -value M2 -port FMC_A1
set_attribute -name PIN_NUMBER -value K1 -port FMC_A2
set_attribute -name PIN_NUMBER -value N2 -port FMC_A3
set_attribute -name PIN_NUMBER -value M1 -port FMC_A4
set_attribute -name PIN_NUMBER -value N1 -port FMC_A5
set_attribute -name PIN_NUMBER -value L2 -port FMC_A6
set_attribute -name PIN_NUMBER -value H1 -port FMC_A7
set_attribute -name PIN_NUMBER -value N3 -port FMC_A8
set_attribute -name PIN_NUMBER -value K2 -port FMC_A9
set_attribute -name PIN_NUMBER -value G1 -port FMC_A10
set_attribute -name PIN_NUMBER -value E1 -port FMC_A11
set_attribute -name PIN_NUMBER -value K7 -port FMC_BURST_CLK
set_attribute -name PIN_NUMBER -value H8 -port FMC_CEn
set_attribute -name PIN_NUMBER -value M7 -port FMC_D0
set_attribute -name PIN_NUMBER -value L7 -port FMC_D1
set_attribute -name PIN_NUMBER -value J6 -port FMC_D2
set_attribute -name PIN_NUMBER -value M6 -port FMC_D3
set_attribute -name PIN_NUMBER -value G2 -port FMC_D4
set_attribute -name PIN_NUMBER -value K3 -port FMC_D5
set_attribute -name PIN_NUMBER -value E2 -port FMC_D6
set_attribute -name PIN_NUMBER -value J3 -port FMC_D7
set_attribute -name PIN_NUMBER -value N4 -port FMC_D8
set_attribute -name PIN_NUMBER -value M4 -port FMC_D9
set_attribute -name PIN_NUMBER -value G4 -port FMC_D10
set_attribute -name PIN_NUMBER -value K5 -port FMC_D11
set_attribute -name PIN_NUMBER -value J5 -port FMC_D12
set_attribute -name PIN_NUMBER -value H6 -port FMC_D13
set_attribute -name PIN_NUMBER -value G6 -port FMC_D14
set_attribute -name PIN_NUMBER -value N7 -port FMC_D15
set_attribute -name PIN_NUMBER -value H7 -port FMC_IRQ0
set_attribute -name PIN_NUMBER -value G7 -port FMC_IRQ1
set_attribute -name PIN_NUMBER -value L5 -port FMC_IRQ2
set_attribute -name PIN_NUMBER -value M5 -port FMC_IRQ3
set_attribute -name PIN_NUMBER -value N6 -port FMC_OEn
set_attribute -name PIN_NUMBER -value G5 -port FMC_WEn
set_attribute -name PIN_NUMBER -value A17 -port FPGA_CAL_TIME_P
set_attribute -name PIN_NUMBER -value A18 -port FPGA_CAL_TIME_N
set_attribute -name PIN_NUMBER -value F17 -port FPGA_CAL_TRIG_P
set_attribute -name PIN_NUMBER -value F18 -port FPGA_CAL_TRIG_N
set_attribute -name PIN_NUMBER -value J4 -port FPGA_CLOCK_P
set_attribute -name PIN_NUMBER -value H4 -port FPGA_CLOCK_N
set_attribute -name PIN_NUMBER -value N24 -port FPGA_DIN
set_attribute -name PIN_NUMBER -value R20 -port FPGA_FLASH_CSn
set_attribute -name PIN_NUMBER -value D16 -port FPGA_GPIO_0
set_attribute -name PIN_NUMBER -value C16 -port FPGA_GPIO_1
set_attribute -name PIN_NUMBER -value W3 -port SENS_SCL
set_attribute -name PIN_NUMBER -value V4 -port SENS_SDA
set_attribute -name PIN_NUMBER -value N23 -port FPGA_MOSI
set_attribute -name PIN_NUMBER -value N21 -port FPGA_PUDC
set_attribute -name PIN_NUMBER -value H3 -port FPGA_SYNC_P
set_attribute -name PIN_NUMBER -value H2 -port FPGA_SYNC_N
set_attribute -name PIN_NUMBER -value B16 -port FPGA_UART_CTS
set_attribute -name PIN_NUMBER -value E17 -port FPGA_UART_RTS
set_attribute -name PIN_NUMBER -value B17 -port FPGA_UART_RX
set_attribute -name PIN_NUMBER -value E18 -port FPGA_UART_TX
set_attribute -name PIN_NUMBER -value R21 -port FTD_UART_CTSn
set_attribute -name PIN_NUMBER -value P21 -port FTD_UART_RTSn
set_attribute -name PIN_NUMBER -value P20 -port FTD_UART_RXD
set_attribute -name PIN_NUMBER -value T20 -port FTD_UART_TXD
set_attribute -name PIN_NUMBER -value V7 -port LED_GREEN
set_attribute -name PIN_NUMBER -value V6 -port LED_ORANGE
set_attribute -name PIN_NUMBER -value U2 -port LED_YELLOW
set_attribute -name PIN_NUMBER -value T3 -port LIS3MDL_DRDY
set_attribute -name PIN_NUMBER -value D15 -port MCU_AFE_SEL
set_attribute -name PIN_NUMBER -value F14 -port MCU_CAL_A0
set_attribute -name PIN_NUMBER -value C13 -port MCU_CAL_MISO
set_attribute -name PIN_NUMBER -value C14 -port MCU_CAL_MOSI
set_attribute -name PIN_NUMBER -value D14 -port MCU_CAL_SS
set_attribute -name PIN_NUMBER -value F3 -port MCU_USART6_RX
set_attribute -name PIN_NUMBER -value F4 -port MCU_USART6_TX
set_attribute -name PIN_NUMBER -value W6 -port MON_ADC1_CONVn
set_attribute -name PIN_NUMBER -value AA3 -port MON_ADC1_CSn
set_attribute -name PIN_NUMBER -value AB4 -port MON_ADC1_SCLK
set_attribute -name PIN_NUMBER -value AA4 -port MON_ADC1_SDI
set_attribute -name PIN_NUMBER -value AB5 -port MON_ADC1_SDO
set_attribute -name PIN_NUMBER -value W4 -port MON_ADC2_CONVn
set_attribute -name PIN_NUMBER -value Y5 -port MON_ADC2_CSn
set_attribute -name PIN_NUMBER -value W5 -port MON_ADC2_SCLK
set_attribute -name PIN_NUMBER -value Y6 -port MON_ADC2_SDI
set_attribute -name PIN_NUMBER -value AA5 -port MON_ADC2_SDO
set_attribute -name PIN_NUMBER -value AC1 -port QOSC_VC_ENA
set_attribute -name PIN_NUMBER -value V2 -port TRIG_IN
set_attribute -name PIN_NUMBER -value U1 -port TRIG_OUT
